import type {
  AgentTarget,
  ArtifactsSnapshot,
  AuditCategory,
  AuditFinding,
  AuditReport,
  Config,
  ConfigSavePayload,
  Initiative,
  InitiativeArtifactStep,
  InitiativePhase,
  InitiativePlanningDecisionType,
  InitiativePlanningQuestion,
  InitiativePlanningQuestionType,
  InitiativePlanningStep,
  InitiativePlanningStepStatus,
  InitiativePlanningSurface,
  InitiativeRefinementState,
  InitiativeWorkflow,
  InitiativeWorkflowStep,
  OperationState,
  OperationStatusRecord,
  PlanningReviewArtifact,
  PlanningReviewFinding,
  PlanningReviewFindingType,
  PlanningReviewKind,
  PlanningReviewStatus,
  ProviderId,
  ProviderKeyStatus,
  InitiativePhaseCheckResult,
  Run,
  RunAttemptDetail,
  RunDetail,
  RunDetailAttemptSummary,
  RunDiffPayload,
  RunListItem,
  RunAttemptRecord,
  RunProgressPayload,
  RunStatePayload,
  SaveProviderKeyPayload,
  SpecDocument,
  SpecDocumentSummary,
  Ticket,
  TicketCoverageArtifact,
  TicketCoverageItem,
  TicketStatus,
  VerificationResult,
  VerificationSeverity,
} from "@specflow/shared-contracts";

export type {
  AgentTarget,
  ArtifactsSnapshot,
  AuditCategory,
  AuditFinding,
  AuditReport,
  Config,
  ConfigSavePayload,
  Initiative,
  InitiativeArtifactStep,
  InitiativePhase,
  InitiativePlanningDecisionType,
  InitiativePlanningQuestion,
  InitiativePlanningQuestionType,
  InitiativePlanningStep,
  InitiativePlanningStepStatus,
  InitiativePlanningSurface,
  InitiativeRefinementState,
  InitiativeWorkflow,
  InitiativeWorkflowStep,
  OperationState,
  OperationStatusRecord,
  PlanningReviewArtifact,
  PlanningReviewFinding,
  PlanningReviewFindingType,
  PlanningReviewKind,
  PlanningReviewStatus,
  ProviderId,
  ProviderKeyStatus,
  InitiativePhaseCheckResult,
  Run,
  RunAttemptDetail,
  RunDetail,
  RunDetailAttemptSummary,
  RunDiffPayload,
  RunListItem,
  RunProgressPayload,
  RunStatePayload,
  SaveProviderKeyPayload,
  SpecDocument,
  SpecDocumentSummary,
  Ticket,
  TicketCoverageArtifact,
  TicketCoverageItem,
  TicketStatus,
  VerificationResult,
  VerificationSeverity,
};

export type RunAttempt = RunAttemptRecord;

export interface ProviderModel {
  id: string;
  name: string;
  contextLength: number | null;
}
